<form action="/auth/authenticate" method="POST" id="User">
    <fieldset>
        <legend>Login</legend>
        <ul>
            <li>
                <label for="email">Email address</label>
                <input id="email" name="email" type="text" />
            </li>
            
            <li>
                <label for="password">Password</label>
                <input name="password" type="password" id="password"/>
            </li>
        </ul>
    </fieldset>
    
    <fieldset class="submit">
        <input type="submit" class="btn btn-default" value="Login..." />
    </fieldset>
    
    <div class="clear"></div>
</form>

<?php

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}